apiVersion: v1
kind: Namespace
metadata:
  name: stage
  labels:
    name: stage

---

apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: stage
spec:
  selector:
    app: flask-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: flask-web
  type: LoadBalancer

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: flask-app
  labels:
    name: flask-app
  namespace: stage
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: ajt89/simple-flask-app:active
        imagePullPolicy: Always
        ports:
            - containerPort: 8080
              protocol: TCP
