kind: Service
apiVersion: v1
metadata:
  name: flask-app
  namespace: stage
spec:
  selector:
    app: flask-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: flask-web
  type: LoadBalancer
