kind: Service
apiVersion: v1
metadata:
  name: locust-k8s-master
  labels:
    name: locust-k8s-master
    role: master
spec:
  ports:
    - port: 8089
      targetPort: locust-ma-web
      protocol: TCP
      name: locust-ma-web
    - port: 5557
      targetPort: locust-ma-p1
      protocol: TCP
      name: locust-ma-p1
    - port: 5558
      targetPort: locust-ma-p2
      protocol: TCP
      name: locust-ma-p2
  selector:
    app: locust-k8s-master
  type: LoadBalancer