kind: Service
apiVersion: v1
metadata:
  name: locust-k8s-master
spec:
  selector:
    app: locust-k8s-master
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
      name: locust-ma-web
    - port: 5557
      targetPort: 5557
      protocol: TCP
      name: locust-ma-p1
    - port: 5558
      targetPort: 5558
      protocol: TCP
      name: locust-ma-p2
  type: LoadBalancer
